version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/burgerput/cicd/deploy


permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: script.sh # Start the script
      timeout: 60
      runas: ubuntu
